CRM/djcrm/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lead/',include('leads.urls'),name='leads')
]

CRM/leads/urls.py
from django.urls import path
from .views import home_page , table_data,table_create,table_update,delete_forms

app_name = 'leads'
urlpatterns = [
    path('',home_page,name='home-forms'),
    path('<int:pk>/',table_data,name='primary-key'),        # here <pk> will be take as a primary key from the domain and send the value from the view func.
    path('create/',table_create,name='create-forms'),        # here <pk> will be take as a primary key from the domain and send the value from the view func.
    path('<int:pk>/update/',table_update,name='update-forms'),
    path('<int:pk>/delete/',delete_forms,name='delete-forms'),
]

    

CRM/leads/models.py
from django.db import models
from django.db.models.enums import Choices


from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
    pass
                            # we can also add some Field like ie.
                            # phone_No = models.IntegerField()

                            # this will allow us to add inbuilded user authentication systems and also help up in to build login systems
                            #  to set up to work need to say django that we are using AUTH_USER_MODEL in setting

class Leads(models.Model):
    first_name=  models.CharField(max_length=15)
    last_name=  models.CharField(max_length=15)
    age = models.IntegerField()
    agent = models.ForeignKey("Agents",on_delete=models.CASCADE)
    def __str__(self) :
        return f"{self.first_name}  {self.last_name}  "


class Agents(models.Model):
    User = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self) :
        return self.User.email
    



#  ---------------------------------------------------------------------------

# class For_just_demo(models.Model):
#     Source_choice = (
#         ('0','Youtube'),
#         ('1','Google'),
#         ('2','Face Book'),
#     )

#     f_name = models.CharField(max_length=50)
#     l_name = models.CharField(max_length=50)
#     age = models.IntegerField(default = 0)

#     phone = models.BooleanField(default = False)
#     source = models.CharField(Choices= Source_choice , default=0,null=False)

#     profile_pic =   models.ImageField(blank=True,null=False)
#     special_files = models.FileField(blank=True,null=False)

CRM/leads/forms.py
from django import forms
from django.db.models import fields
from .models import Leads


class from_table_model(forms.ModelForm):
    class Meta:
        model = Leads
        fields=('first_name','last_name','age','agent')



class form_table(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


    




 

CRM/leads/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from leads.forms import form_table
from .models  import Leads,Agents,User
from .forms import  from_table_model
# Create your views here.

def home_page(request):
    Lead=Leads.objects.all()
    print(Lead)
    a = {
        "name" : "Riken",
        "Lead" : Lead,
        "Aatak" : "Khaddela"
    }
    return render(request,'leads/home.html',a)        
    # return render(request,'secound.html')



def table_data(request,pk):  # here pk will be take the value from the domain like if there is value like 5 than the pk will be 5   <pk> django will take it automaticaly detact it as that we wants to use as the primary key and every pk will be primary key
    # print(pk)                        # i.e  http://127.0.0.1:8000/lead/54   pk will be 54
    sss = Leads.objects.get(id=pk)
    contex = {
        "Lead" : sss,
        "pk" : pk
    }   
    print(sss,'-----------------')                        # i.e  http://127.0.0.1:8000/lead/54   pk will be 54
    return render(request,'leads/secound.html',contex)
    # return HttpResponse(f'This is the table {pk}')
    


def table_create(request):
    print(request.POST)
    req = request.POST
    form = from_table_model()
    if request.method == "POST" :
        print('i got the request')
        form = from_table_model(request.POST)
        if form.is_valid():
            print('this is the valid form')
            form.save()
            print('All Done----------- !')
            return redirect("/lead")

    contex = {
        "Lead" : form,
        "req" : req
    }
    return render(request,'leads/forms.html',contex)
# def table_create(request):
    # print(request.POST)
    # req = request.POST
    # form = from_table_model()
    # if request.method == "POST" :
    #     print('i got the request')
    #     form = from_table_model(request.POST)
    #     if form.is_valid():
    #         print('this is the valid form')
    #         first_name = form.cleaned_data['first_name']
    #         last_name = form.cleaned_data['last_name']
    #         age = form.cleaned_data['age']
    #         agent = Agents.objects.first()

    #         Leads.objects.create(first_name=first_name,last_name=last_name,age=age,agent=agent)
    #         print('All Done----------- !')
    #         return redirect("/lead")

    # contex = {
    #     "Lead" : form,
    #     "req" : req
    # }
    # return render(request,'forms.html',contex)


def table_update(request,pk):
    print(request.POST)
    req = request.POST
    Lead = Leads.objects.get(id=pk)
    form = from_table_model()
    if request.method == "POST" :
        form = from_table_model(request.POST,instance=Lead)
        if form.is_valid():
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            # age = form.cleaned_data['age']
            # Lead.first_name = first_name
            # Lead.last_name = last_name
            # Lead.age = age                         Not require we can do it by django inbuilt functions through add (instace = Lead) in form line : 80      and write direct form.save()   but we can use it when we wants to use it to update any data 

            form.save()
        print('All Done----------- !')
        return redirect("/lead")

    contex = {
        "Lead" : form,
        "req" : req
    }
    # return render(request,'forms.html',contex)


    return render(request,'leads/updateforms.html',contex)

def delete_forms(request,pk):
    Lead = Leads.objects.get(id=pk)
    Lead.delete()
    return redirect("/lead/")

print('Completed')

CRM/leads/templates/leads/forms.html
<!doctype html>
<html lang='en'>
    <head>
    <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css' integrity='sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn' crossorigin='anonymous'>
        <title> Form Feilds </title>

<!--My own style css-->
<style>
label{
    color :rgb(128, 123, 105);
}
</style>
    </head>
    <body>
    <h5 class="mt-3" ><a href="{% url 'leads:home-forms' %}" >Go back to Home</a></h5>
    <hr>

        
        <hr/>
        <div class="container mt-4  border border-dark">
        <h4>Welcome !</h4>
        <form  method="post">
        {% csrf_token %}
        {{Lead.as_p}}
        <button type="submit">Click ME</button>
        </form>
       {{req}}
        <details>
        <summary>About us</summary>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias asperiores nisi labore id itaque quod ipsam sapiente vel ipsum saepe!</p>
    </details> </div> 
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>
    </body>
</html>

CRM/leads/templates/leads/home.html
<!doctype html>
<html lang='en'>
    <head>
    <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>
        <title> This is the home page </title>
    </head>
    <body>
{% comment %} navbar {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
      <div class="container mt-5" >
       <h1>Hello World !</h1> 
       {% for led in Lead %}
       <ul>
           <li> <a href="{% url 'leads:primary-key' led.pk %}"> {{led}}</a> <br>  Age :{{led.age}}  </li>  <!--{ url leads:primary-key' led.pk  }  led.pk is use as to define the primary key in urls from the view functions-->
       </ul>
       {% endfor %}
      
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem omnis quis iure quo possimus molestias, maxime magni, sit in ab ullam non aspernatur illo quos adipisci at laudantium voluptas odio ad nesciunt voluptates sunt! Laudantium hic quia accusantium ducimus? Nobis consectetur ipsa impedit vitae illo. Praesentium dolores delectus tenetur repudiandae.</p>

        <h5>
          <a href="{% url 'leads:create-forms' %}">Create the Lead</a>
        </h5>
        
        </div>
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>
    </body>
</html>

CRM/leads/templates/leads/secound.html
<!doctype html>
<html lang='en'>
    <head>
    <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>
        <title>  </title>
    </head>
    <body>
<!-- navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container">
      <h1>This is the secound  page</h1>
  </div> 
       <h3><a href="{% url 'leads:home-forms' %}">Go back </a></h3>
       {{Lead.pk}}
       <h3><a href="{% url 'leads:update-forms' Lead.pk  %}">Update Forms</a></h3>

       <p>This is the {{Lead}}'s details </p>
       <p>For this agents responsible is {{Lead.agent}}</p>
      
       <h3><a href="{% url 'leads:delete-forms' Lead.pk %}">Delete Forms</a></h3>
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>
    </body>
</html>

{% comment %} /lead/{{pk}}/delete {% endcomment %}

CRM/leads/templates/leads/updateforms.html
<!doctype html>
<!doctype html>
<html lang='en'>
    <head>
    <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>
        <title> Update Forms </title>
    </head>
    <body>
        <!-- added mannual -->
        <h5 class="mt-3" ><a href="{% url 'leads:home-forms' %}" >Go back to Home</a></h5>
        <hr>
        <hr>
        <div class="container mt-4  border border-dark">
        <h4>Update the Forms !</h4>
        <form  method="post">
        {% csrf_token %}
        {{Lead.as_p}}
        <button type="submit">Click me</button>
        </form>
       <!-- {{req}} -->
        <details>
        <summary>About us</summary>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias asperiores nisi labore id itaque quod ipsam sapiente vel ipsum saepe!</p>
    </details> </div> 
         <!-- added mannual -->
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>
    </body>
</html>

CRM/templates/home.html
<!doctype html>
<html lang='en'>
    <head>
    <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
        <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3' crossorigin='anonymous'>
        <title> This is the home page </title>
    </head>
    <body>
{% comment %} navbar {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
      <div class="container mt-5" >
       <h1>Hello World !</h1> 
       {% for led in Lead %}
       <ul>
           <li> <a href="{% url 'leads:primary-key' led.pk %}"> {{led}}</a> <br>  Age :{{led.age}}  </li>  <!--{% url'leads:primary-key' led.pk  %}  led.pk is use as to define the primary key in urls from the view functions-->
       </ul>
       {% endfor %}
      
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem omnis quis iure quo possimus molestias, maxime magni, sit in ab ullam non aspernatur illo quos adipisci at laudantium voluptas odio ad nesciunt voluptates sunt! Laudantium hic quia accusantium ducimus? Nobis consectetur ipsa impedit vitae illo. Praesentium dolores delectus tenetur repudiandae.</p>

        <h5>
          <a href="{% url 'leads:create-forms' %}">Create the Lead</a>
        </h5>
        
        </div>
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p' crossorigin='anonymous'></script>
    </body>
</html>